// 대화문 데이터
// speaker: 'A' | 'B' (대화문), 'N' (독백)
// 타임스탬프는 localStorage에 별도 저장됨 (스탬프 모드로 기록)

export const dialogueData = [
  {
    id: 1,
    title: '그만 게으름 피우고 싶어',
    type: 'dialogue',
    lines: [
      { speaker: 'A', en: 'Do you like to watch movies?' },
      { speaker: 'A', en: 'I like to watch movies when I hang out with my friends.' },
      { speaker: 'B', en: "Well. I stopped watching movies. It's boring." },
      { speaker: 'B', en: 'Actually, I like to listen to music.' },
      { speaker: 'B', en: 'I always listen to music when I take a walk or wear makeup.' },
      { speaker: 'B', en: 'By the way, look at your face!' },
      { speaker: 'B', en: 'Did you take a nap again?' },
      { speaker: 'B', en: 'You should stop slacking off.' },
      { speaker: 'A', en: 'Yes, I took a nap.' },
      { speaker: 'A', en: 'I keep taking a nap and I want to stop taking a nap after I have lunch.' },
    ],
  },
  {
    id: 2,
    title: '나 걔한테 너무 실망했어',
    type: 'dialogue',
    lines: [
      { speaker: 'A', en: 'What did you tell him to do when you were with him?' },
      { speaker: 'A', en: "It's time to tell me." },
      { speaker: 'B', en: 'I told him not to doze off or zone out when he works.' },
      { speaker: 'B', en: 'But he kept making an excuse.' },
      { speaker: 'B', en: 'I was so disappointed at him.' },
      { speaker: 'B', en: 'He was hardworking and I looked forward to his success. But he changed.' },
      { speaker: 'B', en: 'I feel like I wanna cry.' },
      { speaker: 'B', en: "I'm not gonna keep in touch with him forever." },
      { speaker: 'B', en: 'Are you gonna keep in touch with him?' },
    ],
  },
  {
    id: 3,
    title: '돌아와',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "The reason why I can't stop thinking about you is because it's pretty hard to forget you." },
      { speaker: 'N', en: "I can't help thinking about you all the time because I still love you so much." },
      { speaker: 'N', en: 'Do you also come up with me?' },
      { speaker: 'N', en: 'When do you usually come up with me?' },
      { speaker: 'N', en: "Without you, it's too much trouble doing something." },
      { speaker: 'N', en: 'Please come back.' },
    ],
  },
  {
    id: 4,
    title: '난 택시가 좋아',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'Have you ever taken a bus before when you go to work?' },
      { speaker: 'N', en: "I haven't taken a bus because it takes a lot of time to get to my office." },
      { speaker: 'N', en: 'How long have you taken a bus?' },
      { speaker: 'N', en: "Wow, you have taken a bus for 5 years? That's amazing." },
      { speaker: 'N', en: 'Is there a lot of buses?' },
      { speaker: 'N', en: "For me, there is no a lot of buses so I'm not used to taking a bus." },
      { speaker: 'N', en: 'I always take a taxi and I like to talk to myself in a taxi.' },
    ],
  },
  {
    id: 5,
    title: '이사 가고 싶어',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'This building was built in 2001 by force.' },
      { speaker: 'N', en: 'I saw this building by accident and I especially liked the location.' },
      { speaker: 'N', en: 'So I decided to live in this building.' },
      { speaker: 'N', en: 'I have lived in this building since I was 20.' },
      { speaker: 'N', en: "Now, I'm 32." },
      { speaker: 'N', en: "So it's been 12 years since I lived in this building." },
      { speaker: 'N', en: 'One day, I heard that a new building is gonna be built next to my building.' },
      { speaker: 'N', en: "I wanna move out to the new building immediately as soon as it's built." },
    ],
  },
  {
    id: 6,
    title: '출근 전에는 이불 정리를!',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'How often do you make the bed?' },
      { speaker: 'N', en: 'When was the last time you made the bed?' },
      { speaker: 'N', en: 'I heard that making the bed in the morning before you go to work is an important habit to be promoted.' },
      { speaker: 'N', en: 'Your bed always has to be covered with a blanket before you go to work.' },
      { speaker: 'N', en: 'Have you ever made the bed before you go to work?' },
      { speaker: 'N', en: "If you haven't, you should try." },
      { speaker: 'N', en: 'You can trust me.' },
    ],
  },
  {
    id: 7,
    title: '내가 금연 도와줄게!',
    type: 'dialogue',
    lines: [
      { speaker: 'A', en: "I can't stop smoking." },
      { speaker: 'A', en: "I always try to stop smoking but it's too difficult." },
      { speaker: 'A', en: "I don't want to be a man that smells so bad." },
      { speaker: 'A', en: "So I'm looking for some different ways to stop smoking." },
      { speaker: 'A', en: "I can't wait to find a new way that can help me stop smoking." },
      { speaker: 'B', en: 'If you are interested in stopping smoking, I can help you.' },
      { speaker: 'B', en: 'Let me help you.' },
      { speaker: 'B', en: 'Is it okay to help you?' },
      { speaker: 'B', en: "Don't be afraid!" },
    ],
  },
  {
    id: 8,
    title: '나라면 그냥 물어본다',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "Do you think it's the thing that he wants to do?" },
      { speaker: 'N', en: "I don't think it's the thing that he wants to do." },
      { speaker: 'N', en: 'I think you should think more about it.' },
      { speaker: 'N', en: "Honestly, you don't need to think more." },
      { speaker: 'N', en: 'If I were you, I would just ask him the thing that he wants to do.' },
      { speaker: 'N', en: "It seems that he's gonna tell you the thing that he wants to do." },
      { speaker: 'N', en: 'But, you should be careful of the way you ask him because it can offend him.' },
    ],
  },
  {
    id: 9,
    title: '친구가 좋아했던 여자 안 건든다',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "I didn't know she was a person that he liked." },
      { speaker: 'N', en: "I was gonna ask her out but I didn't." },
      { speaker: 'N', en: "I'm sure that he's gonna be offended if I really ask her out." },
      { speaker: 'N', en: "I don't wanna be a person that is shameless." },
      { speaker: 'N', en: "I don't really do something that can ruin my friendship." },
      { speaker: 'N', en: "By the way, can you tell me why he liked her? I'm curious." },
    ],
  },
  {
    id: 10,
    title: '나 그냥 술 마시게 해줘',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "My boyfriend reminds me of my ex-boyfriend because he never lets me drink, too." },
      { speaker: 'N', en: 'Do you know why he never lets me drink?' },
      { speaker: 'N', en: 'Do you want me to tell you the reason?' },
      { speaker: 'N', en: "It's because I always get drunk when I drink." },
      { speaker: 'N', en: "My boyfriend doesn't get it." },
      { speaker: 'N', en: "He doesn't want me to get drunk so he always tries to make me stop drinking." },
      { speaker: 'N', en: 'I got sadder because of him.' },
      { speaker: 'N', en: 'I hope he gets me one day.' },
    ],
  },
  {
    id: 11,
    title: '누가 범인이지?',
    type: 'dialogue',
    lines: [
      { speaker: 'A', en: 'Why are you so blue? What happened?' },
      { speaker: 'B', en: 'Steve and I take the same class and I think he took my wallet in class.' },
      { speaker: 'A', en: 'How about calling the police?' },
      { speaker: 'B', en: 'I should have called the police earlier.' },
      { speaker: 'B', en: "It's too late." },
      { speaker: 'A', en: 'How do you know he took your wallet?' },
      { speaker: 'A', en: 'Why do you think he took your wallet?' },
      { speaker: 'B', en: "It's just my intuition." },
      { speaker: 'B', en: 'Can you help me find out the criminal?' },
      { speaker: 'B', en: 'What is the best way to find out the criminal?' },
    ],
  },
  {
    id: 12,
    title: '그녀의 생일선물 고르기',
    type: 'dialogue',
    lines: [
      { speaker: 'A', en: "I'm not sure if she's gonna like it." },
      { speaker: 'A', en: "I'm sick of choosing her birthday gift." },
      { speaker: 'B', en: 'Well. I think the gift that you chose is prettier than I thought.' },
      { speaker: 'B', en: "There's a good chance that she's gonna like it." },
      { speaker: 'A', en: "Okay. Then I'm gonna give it to her." },
      { speaker: 'A', en: "Thanks to you, I can stop choosing her gift." },
    ],
  },
  {
    id: 13,
    title: '제발 그냥 말해줘',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'Lately, he is strange.' },
      { speaker: 'N', en: 'He swears a lot and he never studies while everybody studies.' },
      { speaker: 'N', en: 'He often spaces out during the class, he always seems bored and he sometimes plays hooky.' },
      { speaker: 'N', en: "I can't stand it anymore." },
      { speaker: 'N', en: 'He is my best friend.' },
      { speaker: 'N', en: 'So, please tell me the truth.' },
      { speaker: 'N', en: 'I was wondering if he is addicted to drugs.' },
      { speaker: 'N', en: "I promise that I'm not gonna tell him." },
      { speaker: 'N', en: "I'm looking for some reason that made him so strange." },
    ],
  },
  {
    id: 14,
    title: '그가 대체 뭘 원하는 걸까',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "As far as I know, my acquaintances talked behind my husband's back a lot." },
      { speaker: 'N', en: 'I think I know why they did that.' },
      { speaker: 'N', en: "It seems that they just looked down on him because he didn't make money." },
      { speaker: 'N', en: 'He always laid around the house and played on his phone.' },
      { speaker: 'N', en: "They didn't know why he didn't make money." },
      { speaker: 'N', en: "The problem is, I don't know, neither." },
      { speaker: 'N', en: 'I wanna know what he wants.' },
    ],
  },
  {
    id: 15,
    title: '보복이 두려워',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'It seems that he is a social butterfly but actually, he is a pushover.' },
      { speaker: 'N', en: 'He is way too kind, so everybody bosses him around and some people even pick a fight with him.' },
      { speaker: 'N', en: 'I think he is bullied at school.' },
      { speaker: 'N', en: "He tosses and turns at night because of them but he doesn't say anything to them because he thinks that they're gonna take revenge on him." },
    ],
  },
  {
    id: 16,
    title: '책은 좋지만 살 빼자',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: "I'm interested in reading books." },
      { speaker: 'N', en: 'It makes me mentally healthy and also I can learn a lot of things by reading books.' },
      { speaker: 'N', en: 'Reading books is generally helpful for me.' },
      { speaker: 'N', en: 'But the problem is, I gain weight.' },
      { speaker: 'N', en: 'I don\'t move when reading books and I just keep eating something when reading books.' },
      { speaker: 'N', en: 'I should lose weight.' },
      { speaker: 'N', en: "I think I'm gonna lose weight by eating like a bird." },
    ],
  },
  {
    id: 17,
    title: '정말 신은 존재하나요?',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'Back in the days, I loved to walk in the park, listening to music.' },
      { speaker: 'N', en: 'And there was a man talking to himself all the time in the park.' },
      { speaker: 'N', en: 'One day, I walked up to him and said "Who are you talking to?"' },
      { speaker: 'N', en: 'He said "No one. I\'m just blaming god. He doesn\'t take care of me. I lost my job and I lost my family. Does god really exist?"' },
      { speaker: 'N', en: "I didn't know what to say." },
    ],
  },
  {
    id: 18,
    title: '퇴근 후 무서운 영화 보기',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'After he leaves work, he always gets moody.' },
      { speaker: 'N', en: "He doesn't know why." },
      { speaker: 'N', en: "He wants to explain what he exactly feels but it's iffy." },
      { speaker: 'N', en: 'He wants to get over it.' },
      { speaker: 'N', en: 'So, he always watches scary movies alone at home with the light off.' },
      { speaker: 'N', en: "He knows it's quite polarizing but he kind of enjoys doing it." },
      { speaker: 'N', en: 'If you are moody after work, you should try.' },
      { speaker: 'N', en: "Let's trust him." },
    ],
  },
  {
    id: 19,
    title: '내가 아싸가 아니라서 다행이야',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'I broke up with my boyfriend last night.' },
      { speaker: 'N', en: 'I was so blue.' },
      { speaker: 'N', en: 'So I decided to drink with my friends.' },
      { speaker: 'N', en: 'As a people person, drinking with my friends at a drinking session is so fun.' },
      { speaker: 'N', en: 'We usually make fun of each other and get hyper.' },
      { speaker: 'N', en: 'Of course, we sometimes whine about our lives.' },
      { speaker: 'N', en: 'Spending time with them helps me relieve my stress.' },
      { speaker: 'N', en: "I'm glad that I'm not an outcast." },
    ],
  },
  {
    id: 20,
    title: '내가 만약 부자라면?',
    type: 'monologue',
    lines: [
      { speaker: 'N', en: 'If you were rich, what would you do?' },
      { speaker: 'N', en: "You haven't thought of it?" },
      { speaker: 'N', en: "Well, I would do everything that I want like it's nothing." },
      { speaker: 'N', en: "No one can tell me off because I'm rich." },
      { speaker: 'N', en: "I would buy 'Teddy Restaurant' and I would eat its food everyday." },
      { speaker: 'N', en: 'This is the best restaurant I have ever been to.' },
      { speaker: 'N', en: 'Nothing would make me have trouble doing something.' },
      { speaker: 'N', en: "I'm excited." },
    ],
  },
]
