# dialogueData.js 와 동기화된 문장 데이터
# generate_timestamps.py 에서 사용

DIALOGUE_LINES = {
    1: [
        "Do you like to watch movies?",
        "I like to watch movies when I hang out with my friends.",
        "Well. I stopped watching movies. It's boring.",
        "Actually, I like to listen to music.",
        "I always listen to music when I take a walk or wear makeup.",
        "By the way, look at your face!",
        "Did you take a nap again?",
        "You should stop slacking off.",
        "Yes, I took a nap.",
        "I keep taking a nap and I want to stop taking a nap after I have lunch.",
    ],
    2: [
        "What did you tell him to do when you were with him?",
        "It's time to tell me.",
        "I told him not to doze off or zone out when he works.",
        "But he kept making an excuse.",
        "I was so disappointed at him.",
        "He was hardworking and I looked forward to his success. But he changed.",
        "I feel like I wanna cry.",
        "I'm not gonna keep in touch with him forever.",
        "Are you gonna keep in touch with him?",
    ],
    3: [
        "The reason why I can't stop thinking about you is because it's pretty hard to forget you.",
        "I can't help thinking about you all the time because I still love you so much.",
        "Do you also come up with me?",
        "When do you usually come up with me?",
        "Without you, it's too much trouble doing something.",
        "Please come back.",
    ],
    4: [
        "Have you ever taken a bus before when you go to work?",
        "I haven't taken a bus because it takes a lot of time to get to my office.",
        "How long have you taken a bus?",
        "Wow, you have taken a bus for 5 years? That's amazing.",
        "Is there a lot of buses?",
        "For me, there is no a lot of buses so I'm not used to taking a bus.",
        "I always take a taxi and I like to talk to myself in a taxi.",
    ],
    5: [
        "This building was built in 2001 by force.",
        "I saw this building by accident and I especially liked the location.",
        "So I decided to live in this building.",
        "I have lived in this building since I was 20.",
        "Now, I'm 32.",
        "So it's been 12 years since I lived in this building.",
        "One day, I heard that a new building is gonna be built next to my building.",
        "I wanna move out to the new building immediately as soon as it's built.",
    ],
    6: [
        "How often do you make the bed?",
        "When was the last time you made the bed?",
        "I heard that making the bed in the morning before you go to work is an important habit to be promoted.",
        "Your bed always has to be covered with a blanket before you go to work.",
        "Have you ever made the bed before you go to work?",
        "If you haven't, you should try.",
        "You can trust me.",
    ],
    7: [
        "I can't stop smoking.",
        "I always try to stop smoking but it's too difficult.",
        "I don't want to be a man that smells so bad.",
        "So I'm looking for some different ways to stop smoking.",
        "I can't wait to find a new way that can help me stop smoking.",
        "If you are interested in stopping smoking, I can help you.",
        "Let me help you.",
        "Is it okay to help you?",
        "Don't be afraid!",
    ],
    8: [
        "Do you think it's the thing that he wants to do?",
        "I don't think it's the thing that he wants to do.",
        "I think you should think more about it.",
        "Honestly, you don't need to think more.",
        "If I were you, I would just ask him the thing that he wants to do.",
        "It seems that he's gonna tell you the thing that he wants to do.",
        "But, you should be careful of the way you ask him because it can offend him.",
    ],
    9: [
        "I didn't know she was a person that he liked.",
        "I was gonna ask her out but I didn't.",
        "I'm sure that he's gonna be offended if I really ask her out.",
        "I don't wanna be a person that is shameless.",
        "I don't really do something that can ruin my friendship.",
        "By the way, can you tell me why he liked her? I'm curious.",
    ],
    10: [
        "My boyfriend reminds me of my ex-boyfriend because he never lets me drink, too.",
        "Do you know why he never lets me drink?",
        "Do you want me to tell you the reason?",
        "It's because I always get drunk when I drink.",
        "My boyfriend doesn't get it.",
        "He doesn't want me to get drunk so he always tries to make me stop drinking.",
        "I got sadder because of him.",
        "I hope he gets me one day.",
    ],
    11: [
        "Why are you so blue? What happened?",
        "Steve and I take the same class and I think he took my wallet in class.",
        "How about calling the police?",
        "I should have called the police earlier.",
        "It's too late.",
        "How do you know he took your wallet?",
        "Why do you think he took your wallet?",
        "It's just my intuition.",
        "Can you help me find out the criminal?",
        "What is the best way to find out the criminal?",
    ],
    12: [
        "I'm not sure if she's gonna like it.",
        "I'm sick of choosing her birthday gift.",
        "Well. I think the gift that you chose is prettier than I thought.",
        "There's a good chance that she's gonna like it.",
        "Okay. Then I'm gonna give it to her.",
        "Thanks to you, I can stop choosing her gift.",
    ],
    13: [
        "Lately, he is strange.",
        "He swears a lot and he never studies while everybody studies.",
        "He often spaces out during the class, he always seems bored and he sometimes plays hooky.",
        "I can't stand it anymore.",
        "He is my best friend.",
        "So, please tell me the truth.",
        "I was wondering if he is addicted to drugs.",
        "I promise that I'm not gonna tell him.",
        "I'm looking for some reason that made him so strange.",
    ],
    14: [
        "As far as I know, my acquaintances talked behind my husband's back a lot.",
        "I think I know why they did that.",
        "It seems that they just looked down on him because he didn't make money.",
        "He always laid around the house and played on his phone.",
        "They didn't know why he didn't make money.",
        "The problem is, I don't know, neither.",
        "I wanna know what he wants.",
    ],
    15: [
        "It seems that he is a social butterfly but actually, he is a pushover.",
        "He is way too kind, so everybody bosses him around and some people even pick a fight with him.",
        "I think he is bullied at school.",
        "He tosses and turns at night because of them but he doesn't say anything to them because he thinks that they're gonna take revenge on him.",
    ],
    16: [
        "I'm interested in reading books.",
        "It makes me mentally healthy and also I can learn a lot of things by reading books.",
        "Reading books is generally helpful for me.",
        "But the problem is, I gain weight.",
        "I don't move when reading books and I just keep eating something when reading books.",
        "I should lose weight.",
        "I think I'm gonna lose weight by eating like a bird.",
    ],
    17: [
        "Back in the days, I loved to walk in the park, listening to music.",
        "And there was a man talking to himself all the time in the park.",
        "One day, I walked up to him and said \"Who are you talking to?\"",
        "He said \"No one. I'm just blaming god. He doesn't take care of me. I lost my job and I lost my family. Does god really exist?\"",
        "I didn't know what to say.",
    ],
    18: [
        "After he leaves work, he always gets moody.",
        "He doesn't know why.",
        "He wants to explain what he exactly feels but it's iffy.",
        "He wants to get over it.",
        "So, he always watches scary movies alone at home with the light off.",
        "He knows it's quite polarizing but he kind of enjoys doing it.",
        "If you are moody after work, you should try.",
        "Let's trust him.",
    ],
    19: [
        "I broke up with my boyfriend last night.",
        "I was so blue.",
        "So I decided to drink with my friends.",
        "As a people person, drinking with my friends at a drinking session is so fun.",
        "We usually make fun of each other and get hyper.",
        "Of course, we sometimes whine about our lives.",
        "Spending time with them helps me relieve my stress.",
        "I'm glad that I'm not an outcast.",
    ],
    20: [
        "If you were rich, what would you do?",
        "You haven't thought of it?",
        "Well, I would do everything that I want like it's nothing.",
        "No one can tell me off because I'm rich.",
        "I would buy 'Teddy Restaurant' and I would eat its food everyday.",
        "This is the best restaurant I have ever been to.",
        "Nothing would make me have trouble doing something.",
        "I'm excited.",
    ],
}
